name: Azure IQ Testing with Pester

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pester-tests:
    runs-on: windows-latest  # Use Windows-based runner

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Install Azure CLI
      - name: Install Azure CLI
        run: |
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile ./azure-cli-installer.msi
          Start-Process msiexec.exe -ArgumentList '/i', './azure-cli-installer.msi', '/quiet', '/norestart' -NoNewWindow -Wait

      # Log in to Azure using Federated credentials
      - name: Authenticate to Azure using Federated Credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          federated-credentials: true
          
      # Install Pester module
      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run Pester Tests
        continue-on-error: true
        run: |
          # Path to the Pester test scripts
          az login --identity
          Invoke-Pester -Script .\az-tests\azure_pester_cli.ps1 -OutputFormat NUnitXml -OutputFile ./test-results/test-results.xml
        shell: pwsh 
      
            # Upload test results to GitHub Actions
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pester-test-results
          path: ./test-results/test-results.xml
