name: Run Pester Tests with Federated Credentials

# Trigger on push to the main branch or on pull requests to the main branch
on:
  push:
    branches:
      - main

jobs:
  pester-test:
    runs-on: mcr.microsoft.com/azure-powershell:mariner-2
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Authenticate to Azure using Federated Credentials
    - name: Authenticate to Azure with Federated Credentials
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Set the client ID in secrets, this is for your Azure App Registration
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Set the tenant ID in secrets
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    # Install Pester module
    - name: Install Pester
      run: |
        pwsh -Command "Install-Module -Name Pester -Force -Scope CurrentUser"

    # Run Pester Tests
    - name: Run Pester Tests
      run: |
        pwsh -Command "Invoke-Pester -Path ./tests -Verbose"  # Path to your test scripts
