name: Print ENV Variable

on:
  push:
    branches:
      - main

jobs:
  print-dev-secret:
    runs-on: ubuntu-latest
    environment: DEV  # Reference the environment here

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print ENV for DEV
        run: |
          echo "The value of ENV for DEV is: $ENV"
        shell: bash

  print-int-secret:
    runs-on: ubuntu-latest
    environment: INT  # Reference the environment here

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print ENV for INT
        run: |
          echo "The value of ENV for INT is: $ENV"
        shell: bash
