name: Print ENV Variable

on:
  push:
    branches:
      - main

jobs:
  print-dev-secret:
    runs-on: windows-latest
    environment: DEV  # Reference the environment here

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print ENV for DEV using PowerShell
        run: |
          echo "The value of ENV for DEV is: $env:ENV"
        shell: pwsh  # Using PowerShell for Windows

  print-int-secret:
    runs-on: windows-latest
    environment: INT  # Reference the environment here

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print ENV for INT using PowerShell
        run: |
          echo "The value of ENV for INT is: $env:ENV"
        shell: pwsh  # Using PowerShell for Windows
