name: Print TEST_SECRET

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment: DEV  # Reference the environment here

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print TEST_SECRET
        run: |
          echo "The value of TEST_SECRET is: ${{ secrets.TEST_SECRET }}"
        shell: bash
