name: Print ENV Variable

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment: DEV  # Reference the environment here

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print ENV
        run: |
          echo "The value of ENV is: ${{ secrets.ENV }}"
        shell: bash
